# Generated by Django 4.2.15 on 2024-08-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Testproject', '0001_initial'),
        ('Scenes', '0002_scenestocase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='任务名称', max_length=50, verbose_name='任务名称')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.PROTECT, to='Testproject.testproject', verbose_name='所属项目')),
                ('scene', models.ManyToManyField(blank=True, help_text='关联的任务流', null=True, to='Scenes.testscent', verbose_name='关联的任务流')),
            ],
            options={
                'verbose_name_plural': '测试任务表',
                'db_table': 'TestTask',
            },
        ),
    ]
