# Generated by Django 4.2.15 on 2024-09-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0002_testrecord_alter_testtask_scene_testreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='create_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, help_text='执行时间', verbose_name='执行时间'),
        ),
    ]
