# Generated by Django 4.2.15 on 2024-08-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Testproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IterFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='接口名称', max_length=50, verbose_name='接口名称')),
                ('url', models.CharField(help_text='接口地址', max_length=50, verbose_name='接口地址')),
                ('method', models.CharField(help_text='请求方法', max_length=20, verbose_name='请求方法')),
                ('type', models.CharField(help_text='接口类型', max_length=50, verbose_name='接口类型')),
                ('project', models.ForeignKey(choices=[{'1': '项目接口', '2': '外部接口'}], help_text='项目id', on_delete=django.db.models.deletion.CASCADE, to='Testproject.testproject', verbose_name='项目id')),
            ],
            options={
                'verbose_name_plural': '接口信息表',
                'db_table': 'interface',
            },
        ),
    ]
