# Generated by Django 4.2.15 on 2024-08-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Testproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='任务流名称', max_length=50, verbose_name='任务流名称')),
                ('project', models.ForeignKey(help_text='所属项目id', on_delete=django.db.models.deletion.PROTECT, to='Testproject.testproject', verbose_name='所属项目id')),
            ],
            options={
                'verbose_name_plural': '任务流信息表',
                'db_table': 'TestScent',
            },
        ),
    ]
