# Generated by Django 4.2.15 on 2024-08-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestInterface', '0002_alter_iterface_project_alter_iterface_type_and_more'),
        ('Scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenesToCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(blank=True, help_text='执行顺序', null=True, verbose_name='执行顺序')),
                ('icase', models.ForeignKey(help_text='接口用例关联id', on_delete=django.db.models.deletion.PROTECT, to='TestInterface.iterfacecase', verbose_name='接口用例关联id')),
                ('scene', models.ForeignKey(help_text='关联的任务流id', on_delete=django.db.models.deletion.PROTECT, to='Scenes.testscent', verbose_name='关联的任务流id')),
            ],
            options={
                'verbose_name_plural': '测试业务流执行步骤',
                'db_table': 'ScenesToCase',
            },
        ),
    ]
